GO ?= go
export CGO_ENABLED = 1

.PHONY: build test test-short test-race test-integration vet lint cover tidy
build:            ; $(GO) build ./...
test:             ; $(GO) test ./...
test-short:       ; $(GO) test -short ./...
test-race:        ; $(GO) test -race ./...
test-integration: ; $(GO) test -tags=integration -timeout=15m ./kafka/...
vet:              ; $(GO) vet ./... && $(GO) vet -tags=integration ./kafka/...
lint:             ; golangci-lint run
cover:            ; $(GO) test -race -coverprofile=coverage.out -covermode=atomic -coverpkg=./kafka/... ./... && $(GO) tool cover -func=coverage.out | tail -1
tidy:             ; $(GO) mod tidy
